### ISSUE TITLE
Wix-style-react coupling

### ISSUE THREAD

**Issue by nktssh** [wix/wix-ui-tpa#139]
Is it possible to make `<Input/>` component tests work without `wix-style-react`? (maybe other component also affected, I didn't check)

We see this code
```
import {inputTestkitFactory} from 'wix-style-react/dist/testkit';
import {inputTestkitFactory as enzymeInputTestkitFactory} from 'wix-style-react/dist/testkit/enzyme';
```
in https://wix-wix-ui-tpa.surge.sh/?activeTab=Testkit&path=%2Fstory%2Fcomponents--input
and it's kinda confusing.
So we have installed `wix-style-react` as dev dependency and all is working now, but I think we should not install it at all

**Comment by jonathanadler** [comment]
This is a bug in the storybook generator util we're using, that's generating the docs.
The example shows how to use the library's testkits.
The intention was to show an example on how to use `wix-ui-tpa`'s testkit.
But the generator added `wix-style-react` instead of `wix-ui-tpa`.
We'll fix this.

So you should use the testkits from this library, and not from `wix-style-react`.

**Comment by nktssh** [comment]
@jonathanadler after changing to import from `wix-ui-tpa` our tests are failing
http://pullrequest-tc.dev.wixpress.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=3589151&_focus=1238
code is 
```
 TypeError: _this.get.groupNameInputDriver(...).enterText is not a function

      34 |     },
      35 |     inputGroupName: (value: string): CreateGroupModalDriver => {
    > 36 |       this.get.groupNameInputDriver().enterText(value);
         |                                       ^
      37 |       return this;
      38 |     },
      39 |     openSelectGroupTypeDropdown: () => {
```
inside the driver
```
get = {
    groupNameInputDriver: () => {
      const dataHook = 'group-name';
      return enzymeInputTestkitFactory({
        wrapper: findByDataHook(this.component, dataHook),
        dataHook,
      });
    },
  };
```
see https://github.com/wix-private/strategic-products/blob/900bd4fe98c8b5ed043eb0b943a10c4a00accad7/social-groups/social-groups-ui/packages/social-groups-app/src/components/modals/CreateGroupModal/CreateGroupModal.driver.tsx#L36

**Comment by nktssh** [comment]
is there any difference between `enzymeInputTestkitFactory` in WRS and wix-ui-tpa?

**Comment by jonathanadler** [comment]
You shouldn't use `wix-style-react`'s testkits for `wix-ui-tpa` components.
They're not the same at all.
It's a bug in the documentation, and shouldn't be working (most of the times).

I suggest you change the testkit to the correct one (`wix-ui-tpa`), and use its API.
If you have an API that's missing from the testkit feel free to open an issue for that.

**Comment by nktssh** [comment]
@jonathanadler I'm trying, and getting the error, see my messages above

**Comment by nktssh** [comment]
Found the reason.
WSR gives us `ReactWrapper` from `enzyme` while `wix-ui-tpa` gives us actual `InputDriver` with custom methods (which is not described btw)

**Comment by nktssh** [comment]
@jonathanadler how does the docs generated now? 
Could they be generated automatically from actual methods from source code?
It's a very confusing now

**Comment by jonathanadler** [comment]
I'm not sure I was clear enough in my previous, so i'll try to elaborate:
The `wix-ui-tpa` has a testkit with two separate drivers: one for enzyme and the other for protractor.
The `wix-ui-tpa/Input` component uses `wix-ui-core/Input` in its implementation.
So the `wix-ui-tpa/Input` enzyme driver uses `wix-ui-core/Input` driver.
Hence this driver's API is a combination of:
https://github.com/wix/wix-ui-tpa/blob/master/src/components/Input/Input.driver.ts and
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/input/Input.driver.ts

And the protractor driver just uses this:
https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/input/Input.protractor.driver.ts

Again, this library has **nothing** to do with `wix-style-react`.
In fact projects that use `wix-ui-tpa` probably shouldn't be using `wix-style-react` as well.

I'm going to close this issue, because again, this is not an issue with the drivers themselves, it's a bug in the documentation generator.

Feel free to contact me if you have any further questions.
